[build-system]
requires = ["setuptools"]
build-backend = "setuptools.backends.legacy:build"

[tool.setuptools]
packages = ["melafit"]

[project]
name = "melafit"
version = "0.1.1"
description = "High-precision 24h melatonin profile analysis"
requires-python = ">=3.12"
license = {text = "MIT"}
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "openpyxl",
    "matplotlib",
]

[project.urls]
Homepage = "https://github.com/vitaliy-ch25/melafit"