[tool.setuptools]
packages = ["melafit"]

[project]
name = "melafit"
version = "0.0.9"
requires-python = ">=3.12"
license = {text = "MIT"}
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "openpyxl",
    "matplotlib",
]

[project.urls]
Homepage = "https://github.com/vitaliy-ch25/melafit"